# -*- coding: utf-8 -*-

# Copyright (C) 2015 - Benjamin Hebgen
# This program is Free Software see LICENSE file for details

EXEC = "exec"
ARGS = "args"
NAME = "name"
ICON = "icon"
BACKGROUND = "background"
SIDECALLS = "sidecalls"
TYPE = "type"
TYPE_APP = "app"
TYPE_FOLDER = "folder"
ALL_APPS_FOLDER = "all apps"
ADDON = xbmcaddon.Addon()
ADDON_VERSION = ADDON.getAddonInfo('version')
ADDON_ID = ADDON.getAddonInfo('id')
ADDON_USER_DATA_FOLDER = xbmc.translatePath("special://profile/addon_data/"+ADDON_ID)
APP_LAUNCHER = xbmc.translatePath("special://home")+ "addons" + os.sep + ADDON_ID + os.sep + "resources" + os.sep + "lib" + os.sep + "AppLauncher.py"
ADDON_STORAGE_FILE = ADDON_USER_DATA_FOLDER + os.sep + "store.json"
ACTION = "action"
ACTION_SHOW_DIR = "showdir"
ACTION_ADD_CUSTOM_VARIANT = "addcustomvariant"
ACTION_ADD_CUSTOM_ENTRY = "addcustomentry"
ACTION_ADD_START_TO_CUSTOM = "addtostart"
ACTION_REMOVE_FROM_START = "removetostart"
ACTION_REMOVE_FROM_CUSTOMS = "removefromcustoms"
ACTION_ADD_CUSTOM_FOLDER = "addcustomfolder"
ACTION_SET_CUSTOM_ICON = "setcustomicon"
ACTION_SET_CUSTOM_BACKGROUND = "setcustombackground"
ACTION_UNSET_CUSTOM_ICON = "unsetcustomicon"
ACTION_UNSET_CUSTOM_BACKGROUND = "unsetcustombackground"
ACTION_MOVE_TO_FOLDER = "movetofolder"
ACTION_EXEC = "exec"
ACTION_FORCE_REFRESH = "forcerefresh"
ARGS_PARAM = "args"
CUSTOM_ENTRIES = "custom"
CUSTOM_ARTS = "arts"
DIR = "dir"
IS_CUSTOM = "iscustom"
PLUGIN_ACTION = "Container.Update(plugin://plugin.program.applauncher?"
DIR_SEP = ADDON.getSetting("dirsep")
CACHE_TIME = int(ADDON.getSetting("cachetime"))
CREATE_CUSTOM_ENTRY_STRING = ADDON.getLocalizedString(35000)
CREATE_CUSTOM_FOLDER_STRING = ADDON.getLocalizedString(35001)
CREATE_CUSTOM_VARIANT_STRING = ADDON.getLocalizedString(35002)
ADD_START_ENTRY_TO_CUSTOMS_STRING = ADDON.getLocalizedString(35003)
REMOVE_CUSTOM_ENTRY_STRING = ADDON.getLocalizedString(35004)
MOVE_TO_FOLDER_STRING = ADDON.getLocalizedString(35005)
FORCE_REFRESH_STRING = ADDON.getLocalizedString(35006)
SET_CUSTOM_ICON_STRING = ADDON.getLocalizedString(35007)
SET_CUSTOM_BACKGROUND_STRING = ADDON.getLocalizedString(35008)
UNSET_CUSTOM_ICON_STRING = ADDON.getLocalizedString(35009)
UNSET_CUSTOM_BACKGROUND_STRING = ADDON.getLocalizedString(35010)
ICON_TITLE_STRING = ADDON.getLocalizedString(35011)
BACKGROUND_TITLE_STRING = ADDON.getLocalizedString(35012)
SELECT_EXECUTION_FILE_STRING = ADDON.getLocalizedString(35013)
ADD_PARAMETERS_STRING = ADDON.getLocalizedString(35014)
SET_NAME_STRING = ADDON.getLocalizedString(35015)
ADD_FOLDER_STRING = ADDON.getLocalizedString(35016)
MOVE_ENTRY_TO_FOLDER_STRING = ADDON.getLocalizedString(35017)
HEADER_FAIL_CUSTOM_ENTRY_STRING = ADDON.getLocalizedString(35018)
CUSTOM_FOLDER_CREATION_FAIL_STRING = ADDON.getLocalizedString(35019)
MODE = "mode"
MODE_GAMES = "games"
MODE_GAMES_ID = 1
MODE_ALL_ID = 0
